---
name: Test-Cookbook
version: 0.02
author:
  - 'Khemir Nadim ibn Hamouda. <nadim@khemir.net>'
abstract: "Write your tests as cookbooks\n"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Compare: 0
  Data::TreeDumper: 0
  Filter::Simple: 0
  IO::String: 0
  POD::Tested: 0.03
  Readonly: 0
  Sub::Exporter: 0
  Test::Block: 0
  Test::Dependencies: 0
  Test::Distribution: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
  Test::Strict: 0
  Test::Warn: 0
  version: 0.5
provides:
  Test::Cookbook:
    file: lib/Test/Cookbook.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
